import { useEffect, useState } from "react";
import { Link, useParams } from "react-router-dom";
import { motion } from "framer-motion";

const apiBaseUrl = "https://shree-backend-eta.vercel.app"; // use for local run || "http://localhost:3000"

export default function CandidateCertificate() {
  const { id } = useParams();
  const [candidate, setCandidate] = useState(null);
  const [status, setStatus] = useState({ type: "loading", message: "" });

  const formatDateTime = (value) => {
    if (!value) return "-";
    const date = new Date(value);
    if (Number.isNaN(date.getTime())) return "-";
    return date.toLocaleString("en-IN", {
      year: "numeric",
      month: "short",
      day: "2-digit",
      hour: "2-digit",
      minute: "2-digit",
    });
  };

  const detailItems = [
    { label: "Candidate Name", value: candidate?.name || "-" },
    { label: "Internship ID", value: candidate?.internshipId || "-" },
    { label: "Course", value: candidate?.course || "-" },
    { label: "Duration", value: candidate?.duration || "-" },
    { label: "Record ID", value: candidate?._id || "-" },
    { label: "Created", value: formatDateTime(candidate?.createdAt) },
    { label: "Last Updated", value: formatDateTime(candidate?.updatedAt) },
  ];

  useEffect(() => {
    let isActive = true;

    const loadCandidate = async () => {
      setStatus({ type: "loading", message: "" });

      try {
        const response = await fetch(`${apiBaseUrl}/api/candidates/${id}`);
        const payload = await response.json();

        if (!response.ok) {
          throw new Error(payload?.message || "Unable to fetch candidate.");
        }

        if (isActive) {
          setCandidate(payload);
          setStatus({ type: "success", message: "" });
        }
      } catch (error) {
        if (isActive) {
          setCandidate(null);
          setStatus({ type: "error", message: error.message || "Unable to load candidate." });
        }
      }
    };

    if (id) {
      loadCandidate();
    }

    return () => {
      isActive = false;
    };
  }, [id]);

  if (status.type === "error") {
    return (
      <div className="mx-auto max-w-5xl px-4 py-12 sm:px-6 md:px-12">
        <motion.div
          initial={{ opacity: 0, y: 16 }}
          animate={{ opacity: 1, y: 0 }}
          transition={{ duration: 0.4 }}
          className="rounded-3xl border border-white/70 bg-white/70 p-8 shadow-glow backdrop-blur"
        >
          <h1 className="text-2xl font-semibold text-midnight">Candidate not found</h1>
          <p className="mt-3 text-slate-600">{status.message}</p>
          <Link
            to="/"
            className="mt-6 inline-flex items-center rounded-full bg-midnight px-6 py-3 text-sm font-semibold uppercase tracking-[0.2em] text-white transition hover:bg-slateink"
          >
            Back to home
          </Link>
        </motion.div>
      </div>
    );
  }

  return (
    <div className="mx-auto max-w-6xl px-4 py-10 sm:px-6 md:px-12">
      <motion.header
        initial={{ opacity: 0, y: 16 }}
        animate={{ opacity: 1, y: 0 }}
        transition={{ duration: 0.5 }}
        className="flex flex-col gap-4"
      >
        <p className="text-sm uppercase tracking-[0.35em] text-slate-500">Certificate Portal</p>
        <h1 className="text-3xl font-semibold text-midnight sm:text-4xl">Candidate Certificate</h1>
        <p className="max-w-2xl text-base text-slate-600">
          View the verified internship certificate and the complete candidate record below.
        </p>
      </motion.header>

      <div className="mt-10 grid gap-8 lg:grid-cols-[minmax(0,1fr)_360px]">
        <motion.section
          initial={{ opacity: 0, y: 20 }}
          animate={{ opacity: 1, y: 0 }}
          transition={{ duration: 0.5, delay: 0.1 }}
          className="overflow-hidden rounded-3xl border border-white/70 bg-white/70 shadow-glow backdrop-blur"
        >
          <div className="border-b border-white/70 px-6 py-5">
            <div className="flex flex-wrap items-center gap-3">
              <div className="inline-flex items-center gap-2 rounded-full bg-emerald-50 px-3 py-1 text-xs font-semibold uppercase tracking-[0.2em] text-emerald-600">
                Verified
              </div>
              <div className="text-sm text-slate-500">
                Reference: <span className="font-semibold text-slate-700">{candidate?.internshipId || "-"}</span>
              </div>
            </div>
            <p className="mt-2 text-base text-slate-600">
              This PDF is the official certificate generated by Appliance Care Hub.
            </p>
          </div>

          {status.type === "loading" ? (
            <div className="flex h-[720px] items-center justify-center text-slate-600">Loading certificate...</div>
          ) : candidate?.certificateUrl ? (
            <iframe
              title="Candidate certificate"
              src={candidate.certificateUrl}
              className="h-[720px] w-full"
            />
          ) : (
            <div className="flex h-[720px] items-center justify-center text-slate-600">
              Certificate has not been uploaded yet.
            </div>
          )}
        </motion.section>

        <motion.aside
          initial={{ opacity: 0, y: 20 }}
          animate={{ opacity: 1, y: 0 }}
          transition={{ duration: 0.5, delay: 0.2 }}
          className="rounded-3xl border border-white/70 bg-white/70 p-6 shadow-glow backdrop-blur"
        >
          <h2 className="text-xl font-semibold text-midnight">Candidate Details</h2>
          <div className="mt-5 grid gap-4 text-sm text-slate-700">
            {detailItems.map((item) => (
              <div key={item.label} className="rounded-2xl border border-white/60 bg-white/60 px-4 py-3">
                <p className="text-[11px] uppercase tracking-[0.22em] text-slate-400">{item.label}</p>
                <p className="mt-1 text-base font-semibold text-midnight">{item.value}</p>
              </div>
            ))}
          </div>

          {candidate?.certificateUrl ? (
            <a
              href={candidate.certificateUrl}
              target="_blank"
              rel="noreferrer"
              className="mt-6 inline-flex w-full items-center justify-center rounded-full bg-midnight px-5 py-3 text-sm font-semibold uppercase tracking-[0.2em] text-white transition hover:bg-slateink"
            >
              Open Certificate PDF
            </a>
          ) : null}

          <Link
            to="/"
            className="mt-3 inline-flex w-full items-center justify-center rounded-full border border-slate-200 px-5 py-3 text-sm font-semibold uppercase tracking-[0.2em] text-slate-600 transition hover:border-slate-300 hover:text-slate-800"
          >
            Back to home
          </Link>
        </motion.aside>
      </div>
    </div>
  );
}
